apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicdmeta-demo3
  namespace: cicdmeta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicdmeta-demo3
  template:
    metadata:
      labels:
        app: cicdmeta-demo3
    spec:
      containers:
      - name: cicdmeta-demo3-container
        image: cicdmeta-demo3
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
        ports:
        - containerPort: 8000
        env:
        - name: CICDMETA_ENV
          value: "prod"
