apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cicdmeta-demo3-ingress
  namespace: cicdmeta
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/group.name: global-infra
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/conditions.cicdmeta-demo3-service-feat1: >
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "X-ENV", "values":["feat1"]}}]
spec:
  rules:
  - host: demo3.cicdmeta.zilliz.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cicdmeta-demo3-service
            port:
              number: 8000
  - host: demo3.cicdmeta.zilliz.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cicdmeta-demo3-service-feat1
            port:
              number: 8000
