apiVersion: v1
kind: Service
metadata:
  name: cicdmeta-demo1-service  #appfactory
  namespace: cicdmeta
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: cicdmeta-demo1  #appfactory
